import { prisma } from "@/lib/prisma";
import { auth, currentUser } from "@clerk/nextjs/server";
import { NextResponse } from "next/server";

export async function GET() {
    const { userId } = await auth();

    if (!userId) {
        return new NextResponse(`Unauthorized`, { status: 401 });
    }

    // Get user info
    const user = await currentUser();

    if (!user) {
        return new NextResponse(`User doesn't exist`, { status: 401 });
    }

    let dbUser = await prisma.user.findUnique({
        where: {
            clerkUserId: user.id,
        },
    });

    if (!dbUser) {
        const userData = {
            id: undefined, // `id` will be auto-generated by Prisma with `cuid()`
            clerkUserId: user.id,
            email: user.emailAddresses?.[0]?.emailAddress ?? '',
            firstName: user.firstName ?? null,
            lastName: user.lastName ?? null,
            isAdmin: false, // Default value
            createdAt: undefined, // `createdAt` will be auto-generated by Prisma with `now()`
        };

        // Log the userData object
        console.log('Creating new user with data:', userData);

        dbUser = await prisma.user.create({
            data: userData,
        });
    }

    // Perform redirect with returned user object
    return new NextResponse(null, {
        status: 302,
        headers: {
            Location: '/create-event',
        },
    });
}